import React, { useCallback, useEffect, useState } from 'react';
import {
  ActivityIndicator,
  Modal,
  Pressable,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { PassageText } from './PassageText';
import { Button } from '@/components/Button';
import { colors, radius } from '@/theme/tokens';
import { fonts } from '@/theme/typography';
import { generatePassage, type Absurdity } from '@/data/ai';
import type { CollectedWord } from '@/types/models';

interface StoryTabProps {
  words: CollectedWord[];
}

const LEVELS: { key: Absurdity; emoji: string; label: string }[] = [
  { key: 'low', emoji: '😐', label: 'Mild' },
  { key: 'medium', emoji: '😄', label: 'Absurd' },
  { key: 'high', emoji: '🤪', label: 'Unhinged' },
];

export function StoryTab({ words }: StoryTabProps) {
  const [absurdity, setAbsurdity] = useState<Absurdity>('medium');
  const [passage, setPassage] = useState('');
  const [loading, setLoading] = useState(true);
  const [fromAI, setFromAI] = useState(false);
  const [popover, setPopover] = useState<{ word: string; def: string } | null>(null);

  const vocab = React.useMemo(
    () => Object.fromEntries(words.map((w) => [w.word, w.definition])),
    [words],
  );

  const generate = useCallback(async () => {
    if (words.length === 0) {
      setLoading(false);
      return;
    }
    setLoading(true);
    const targets = words.slice(0, 8).map((w) => w.word);
    const result = await generatePassage(targets, absurdity);
    setPassage(result.text);
    setFromAI(result.fromAI);
    setLoading(false);
  }, [words, absurdity]);

  useEffect(() => {
    generate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [absurdity]);

  if (words.length === 0) {
    return (
      <Text style={styles.empty}>
        Solve a puzzle to collect words, then they'll show up here woven into
        a story.
      </Text>
    );
  }

  return (
    <View>
      <View style={styles.headerCard}>
        <View style={styles.robotIcon}>
          <Text style={{ fontSize: 18 }}>🤖</Text>
        </View>
        <View style={{ flex: 1 }}>
          <Text style={styles.headerTitle}>AI Context Story</Text>
          <Text style={styles.headerSub}>
            Targeting your {Math.min(words.length, 8)} most urgent words
          </Text>
        </View>
        <View style={styles.wordBadge}>
          <Text style={styles.wordBadgeText}>{Math.min(words.length, 8)} words</Text>
        </View>
      </View>

      {/* Absurdity selector */}
      <View style={styles.levelRow}>
        {LEVELS.map((lvl) => {
          const active = lvl.key === absurdity;
          return (
            <Pressable
              key={lvl.key}
              onPress={() => setAbsurdity(lvl.key)}
              style={[styles.levelPill, active && styles.levelPillActive]}
            >
              <Text style={styles.levelEmoji}>{lvl.emoji}</Text>
              <Text style={[styles.levelLabel, active && { color: colors.yellow }]}>
                {lvl.label}
              </Text>
            </Pressable>
          );
        })}
      </View>

      {/* Passage card */}
      <View style={styles.passageCard}>
        <Text style={styles.quoteMark}>"</Text>
        {loading ? (
          <View style={styles.loading}>
            <ActivityIndicator color={colors.yellow} />
            <Text style={styles.loadingText}>Writing your story…</Text>
          </View>
        ) : (
          <PassageText
            passage={passage}
            vocab={vocab}
            onWordPress={(word, def) => setPopover({ word, def })}
          />
        )}
        {!loading && (
          <Text style={styles.source}>
            {fromAI ? '✨ Generated by Claude' : '○ Offline sample passage'}
          </Text>
        )}
      </View>

      <Button
        label="✨ Generate New Story"
        onPress={generate}
        disabled={loading}
        style={{ marginTop: 12 }}
      />

      {/* Definition popover */}
      <Modal
        visible={popover !== null}
        transparent
        animationType="fade"
        onRequestClose={() => setPopover(null)}
      >
        <Pressable style={styles.backdrop} onPress={() => setPopover(null)}>
          <View style={styles.popover}>
            <Text style={styles.popoverWord}>{popover?.word}</Text>
            <Text style={styles.popoverDef}>{popover?.def}</Text>
          </View>
        </Pressable>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  empty: {
    fontFamily: fonts.body,
    fontSize: 12.5,
    color: colors.textMuted,
    textAlign: 'center',
    marginTop: 30,
    lineHeight: 19,
  },
  headerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: colors.surface,
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
  },
  robotIcon: {
    width: 38,
    height: 38,
    borderRadius: 11,
    backgroundColor: 'rgba(99,102,241,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontFamily: fonts.bodyExtra,
    fontSize: 14,
    color: colors.text,
  },
  headerSub: {
    fontFamily: fonts.body,
    fontSize: 11,
    color: colors.textMuted,
    marginTop: 1,
  },
  wordBadge: {
    backgroundColor: 'rgba(52,211,153,0.16)',
    borderRadius: radius.pill,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  wordBadgeText: {
    fontFamily: fonts.bodyExtra,
    fontSize: 10,
    color: colors.mint,
  },
  levelRow: {
    flexDirection: 'row',
    gap: 7,
    marginTop: 12,
  },
  levelPill: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 5,
    paddingVertical: 9,
    borderRadius: radius.pill,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  levelPillActive: {
    backgroundColor: 'rgba(255,229,102,0.1)',
    borderColor: 'rgba(255,229,102,0.4)',
  },
  levelEmoji: { fontSize: 13 },
  levelLabel: {
    fontFamily: fonts.bodyExtra,
    fontSize: 11,
    color: colors.textMuted,
    letterSpacing: 0.3,
  },
  passageCard: {
    backgroundColor: '#0F1E30',
    borderRadius: radius.cardLarge,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 18,
    paddingTop: 26,
    marginTop: 12,
    minHeight: 200,
  },
  quoteMark: {
    position: 'absolute',
    top: 2,
    left: 12,
    fontFamily: fonts.serif,
    fontSize: 56,
    color: 'rgba(255,229,102,0.16)',
  },
  loading: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 50,
    gap: 12,
  },
  loadingText: {
    fontFamily: fonts.body,
    fontSize: 12,
    color: colors.textMuted,
  },
  source: {
    fontFamily: fonts.bodyBold,
    fontSize: 9.5,
    color: colors.textDim,
    marginTop: 14,
  },
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 30,
  },
  popover: {
    backgroundColor: colors.card,
    borderRadius: radius.modal,
    borderWidth: 1,
    borderColor: 'rgba(255,229,102,0.3)',
    padding: 20,
    width: '100%',
  },
  popoverWord: {
    fontFamily: fonts.display,
    fontSize: 22,
    color: colors.yellow,
  },
  popoverDef: {
    fontFamily: fonts.serif,
    fontSize: 14,
    color: colors.text,
    lineHeight: 21,
    marginTop: 6,
  },
});
