"""
Quality pass over data/definitions.json:

1. Drop definition candidates (primary or alternate) that are citations /
   cross-references rather than definitions: "See Barytone",
   "Of Lie. See lain. Ps. lxviii", ", pl. of Villus", "imp. & p. p. of Run".
   These read as broken clues and teach nothing.
2. Drop trivially short candidates (< 4 chars: ADO's "Do").
3. Remove every source=="inflection" candidate — enrich_definitions is
   re-run after this script with the fixed engine, regenerating them
   without the grammar bugs ('exerciseses', 'Someones who works').
4. Promote the first surviving candidate to primary; delete words whose
   candidates all fail (they fall through to hand clues or the gap pass).

Run:  python3 clean_definitions.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

HERE = Path(__file__).parent
DEFS_PATH = HERE / "data" / "definitions.json"

CITATION = re.compile(
    r"\bSee [A-Z]"
    r"|\bCf\."
    r"|\bpl\. of\b|\bPl\. of\b|^pl\b|^Pl\b\.?$"
    r"|\bimp\.\s*(&|and)\s*p\. p\b|\bimp\. of\b|\bp\. p\. of\b|\bimp\b\. &"
    r"|^Of [A-Z][a-z]+\.?($| )"
    r"|\b(?:Acts|Ps|Gen|Matt|Cor|Rom|Luke|John|Rev|Deut|Exod|Isa|Heb"
    r"|Sam|Chron|Prov|Eccl)\.? [ivxlc]+\b"
)


def is_junk(text: str) -> bool:
    t = text.strip()
    if len(t) < 4:
        return True
    if CITATION.search(t):
        return True
    return False


def main() -> None:
    defs = json.loads(DEFS_PATH.read_text())
    n_junk = n_inflection = n_promoted = n_deleted = 0

    cleaned: dict[str, dict] = {}
    for word, entry in defs.items():
        candidates = [entry] + entry.get("alternates", [])
        survivors = []
        for cand in candidates:
            if cand.get("source") == "inflection":
                n_inflection += 1
                continue
            if is_junk(cand.get("definition", "")):
                n_junk += 1
                continue
            survivors.append(cand)
        if not survivors:
            n_deleted += 1
            continue
        head = dict(survivors[0])
        rest = [
            {k: v for k, v in c.items() if k != "alternates"}
            for c in survivors[1:]
        ]
        if rest:
            head["alternates"] = rest
        else:
            head.pop("alternates", None)
        if survivors[0] is not candidates[0]:
            n_promoted += 1
        cleaned[word] = head

    DEFS_PATH.write_text(json.dumps(cleaned, indent=1))
    print(f"entries in:            {len(defs):,}")
    print(f"entries out:           {len(cleaned):,}")
    print(f"junk candidates cut:   {n_junk:,}")
    print(f"inflection cands cut:  {n_inflection:,} (regenerated by enrich)")
    print(f"alternates promoted:   {n_promoted:,}")
    print(f"words deleted:         {n_deleted:,}")


if __name__ == "__main__":
    main()
